//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW_Special_Sites.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>463501768,bbrodie@paymentworld.com,https://apps.paymentworld.com/?id=c74c1acf-6fe1-460a-b9d6-fe841ea59520,(855) 282-6510 ext 2205</string>
  <string>319135322,elena@paymentworld.com,https://apps.paymentworld.com/?id=c74c1acf-6fe1-460a-b9d6-fe841ea59520, (855) 282-6510 ext 2204</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AgentSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AgentSettings"]));
            }
        }
    }
}
